---
#Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
   - name: shutdown load balancer
     service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
    - name: shutdown webserver
      service: name=apache2 state=stopped
#Restart mysql

- hosts: database
  become: true
  tasks:
    - name: restart sql server
      service: name=mysql state=restarted

#Bring stack up

- hosts: webserver
  become: true
  tasks:
   - name: start webserver
     service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
   - name: start load balancer
     service: name=nginx state=started


